- src/fastq/call_consensus_reads/calc_consensus.rs
- src/fastq/call_consensus_reads/pipeline.rs
Unraveled functions within calc_consensus.rs by creating trait and structs.
Shared code is now implemented within trait.
This should increase the maintainability for future changes.
> Generalized calc_consensus.rs

- src/fastq/call_consensus_reads/pipeline.rs
There is no need to allocate the vector of distances only to convert it into an iterator for the streaming-stats::median function.
> Avoid allocating vector

- test-consensus.1.fastq
- test-consensus.2.fastq
There were two test files added to the root directory in a previous pull request by mistake.
> Removed unnecessary test files from root

- src/fastq/call_consensus_reads/pipeline.rs
Similar to #19 allocation of a vector can be avoided by chaining iterators.
> Refactor slightly to avoid vector allocation

- CHANGELOG.md
- README.md
I updated the changelog for the next release (which only makes changes to `call-consensus-reads`) and added `call-consensus-reads` to the main readme.
> 3.1.0 docs

- src/fastq/call_consensus_reads/pipeline.rs
The code comments were outdated and did not reflect the current structure of clustering calls. This PR fixes that.
> Updated code comments to new structure of clustering

- README.md
Add standard cargo install instructions and differentiate this from installing via cargo from source
> Add cargo install instructions

- src/bcf/report/oncoprint.rs
This PR fixes https://github.com/rust-bio/rust-bio-tools/issues/77 by updating the handling of format data from single sample to multi sample VCFs.
> Fix index out of bounce error in vcf-report

- src/bcf/annotate_dgidb.rs
- src/bcf/split.rs
Just as the title says only two small fixes to please clippy. There is still one lint occurring that should be fixed with #88.
> Fix two clippy lints

- Cargo.toml
- src/bam/collapse_reads_to_fragments/pipeline.rs
- src/bam/depth.rs
- src/bcf/annotate_dgidb.rs
- src/bcf/baf.rs
- src/bcf/match_variants.rs
- src/bcf/report/oncoprint.rs
- src/bcf/report/table_report/alignment_reader.rs
- src/bcf/report/table_report/create_report_table.rs
- src/bcf/report/table_report/mod.rs
- src/bcf/split.rs
- src/bcf/to_txt.rs
I was experiencing the same problem as described [here](https://github.com/samtools/htslib/pull/1143) on my mac so I saw this as an opportunity to upgrade `rust-htslib`. I had to change a few things here and there for everything to compile and work as expected by the tests. I had to add a few `clone()` statements for the the new buffers. It'd be great if you'd check these @johanneskoester since I am not 100% sure if that's the way to go. I also fixed some clippy lints while I was at it. This is still WIP until a new version of  `rust-htslib` is released (https://github.com/rust-bio/rust-htslib/issues/283).
> Upgrade rust-htslib version

- src/bcf/report/oncoprint.rs
This PR fixes a bug with a wrong removal index when trying to remove the existing variation and clin sig plots.
> Fix wrong removal index bug

- src/bcf/report/html/empty_report.html.tera
- src/bcf/report/oncoprint.rs
This PR adds an html page with "no variants found" for the given case.
> Add index page when no variants are found

- src/bcf/report/table_report/alignment_reader.rs
- src/bcf/report/table_report/mod.rs
Just a quick PR with some minor improvements from the newest nightly clippy version that pointed out a few code improvements that really made sense to me. I also added a clippy label for any upcoming potential PRs that only apply clippy lints.
> Some more clippy lints

- src/csv/csv_report.css
- src/csv/csv_report.html.tera
- src/csv/csv_report.js.tera
- src/csv/plot.js.tera
- src/csv/report.rs
This PR lets the user highlight specific values from their data in the according histogram.
> Plot numeric values in csv-report

- src/bam/collapse_reads_to_fragments/pipeline.rs
- src/bcf/match_variants.rs
- src/bcf/report/oncoprint.rs
- src/bcf/split.rs
- src/fastq/collapse_reads_to_fragments/pipeline.rs
Just a quick PR that applies the latest lints from clippy and 2 warnings that came up with the latest version of rust.
> Apply latest clippy lints

- src/csv/report.rs
This PR fixes `thread 'main' panicked at 'internal error: entered unreachable code', src/csv/report.rs:72:18` that occurred with `rbt csv-report an_empty_file.csv`.
> fix: csv-report for empty files

- src/bcf/report/js/table-report.js
This adds a link for Cosmic genomic mutation identifiers (COSV).
> feat: Add linkout for COSV entries

- Cargo.toml
- src/bam/anonymize_reads.rs
- src/bam/plot/plot_bam.rs
- src/bcf/report/table_report/alignment_reader.rs
- src/bcf/report/table_report/create_report_table.rs
- src/bcf/report/table_report/fasta_reader.rs
- src/bcf/report/table_report/static_reader.rs
- src/fastq/collapse_reads_to_fragments/mod.rs
- src/fastq/collapse_reads_to_fragments/pipeline.rs
> feat: Update rust-bio

- src/bcf/report/oncoprint.rs
- src/bcf/report/table_report/create_report_table.rs
Just a quick PR that fixes #205.
> fix: Add error messages for missing annotations

- src/bcf/report/report.html.tera
- tests/expected/report/details/a/ENST00000557334_5_c_35G_A.html
- tests/expected/report/details/b/ENST00000557334_5_c_35G_A.html
- tests/expected/report/genes/KRAS1.html
- tests/expected/report/indexes/index1.html
- tests/lib.rs
This adds tests which have not been pushed in the previous PR.
> fix: vcf-report tests

- src/bcf/report/js/gene-report.js
This PR fixes broken links for alterations containing multiple special characters.
> fix: Fix possible broken link to third stage of vcf-report

- src/bcf/report/table_report/create_report_table.rs
This PR changes the behavior of the vcf-report for variants without `HGVSg`. Now the report will skip the variant and the user will receive a warning with the variant id and position. Beforehand the vcf-report would throw an error if such a variant occurred in the input.
> feat: Warn instead of panic for missing HGVSg values in vcf-report

- src/bcf/report/table_report/create_report_table.rs
Just a quick PR that fixes #230.
> fix: Report 1-based position in vcf-report log messages

- .github/dependabot.yml
As discussed with @dlaehnemann in #257 this PR sets up dependabot to update dependencies of rust-bio-tools weekly.
> chore: Setup dependabot
