src/bcf/match_variants.rs

This fixes a regression in nightly due to the pending stabilization of `Iterator::flatten`.
See https://github.com/rust-lang/rust/pull/51511 for details.

Fix Itertools::flatten regression in nightly

---

Cargo.toml
src/fastq/call_consensus_reads/mod.rs
src/main.rs

Reverted error handling with the failure crate and refactored the main function to return error. Now errors (and stack traces) reach the terminal.
This PR removes nicely readable error messages for the `call_consensus_reads` tool. These will return after the errors returned by the rust-bio readers/ writers have been reworked.

Error handling reloaded

---

src/main.rs

I think we can remove the early-return `(?)` followed by `Ok(())` as it's redundant:
each subcommand returns a `Result<(), Error>` anyway, or am I missing something?

Use matching rather than if-else to call subcommands

---

Cargo.toml
src/fastq/call_consensus_reads/pipeline.rs

This PR adds user feedback to the call-consensus-reads tool. For the first clustering pass, the number of reads analyzed is shown. In the second clustering the number of processed clusters/ UMIs is reported.
The output is written to stderr, if run in a terminal. If stderr is piped into a file, no output is written.

Improved user feedback.

---

src/cli.yaml
src/main.rs

This PR renames the parameter in call-consensus-reads which is used to denote that the UMI is located on the reverse read. The current name of that parameter (`--reverse-umi`) might be easily confused with other meanings of reverse (like reverse complement etc.).

Renamed parameter to avoid confusion with a reverse UMI

---

.gitignore
src/bcf/annotate_dgidb.rs
src/cli.yaml
src/main.rs

This PR fixes a bug where annotation of dgidb interaction drugs fails if the input vcf contains too many genes.
The error originates from a too long url, build from the genes contained in the vcf file.
To resolve this issue the subcommand now performs multiple api requests instead of a single one, only submitting 1000 genes per request.
To circumvent future issues the subcommand now also has a new parameter `genes-per-requests` allowing to adjust the number of genes being submitted by each request.
This value should be as high as possible for keeping the number of requests low.

Chunkwise api requests in annotate-dgidb subcommand

---

src/cli.yaml
src/fastq/call_consensus_reads/mod.rs

Since the bam version of call-consensus-read has been added, an additional subcommand is required.

Fixed syntax of call-consensus-reads usage examples

---

src/cli.yaml

This PR reduces the number of genes submitted per dgidb-api request to 500.
It showed, that submitting 1000 genes at once may return a http-request error.
To ensure that the gene-string does not exceed the request limitations the number of genes has been reduced.

Reduced number of genes per request

---

.cargo/config

This PR adds a config file with linker arguments required for building on macOS.

Added linker arguments for macOS

---

src/bcf/oncoprint.rs
src/cli.yaml
src/main.rs

This adds a flag `--vep-annotation` to the oncoprint submodule allowing to correctly parse bcf-files annotated by VEP.

Oncoprint: Parse ANN field as defined by VEP

---

src/bcf/report/table_report/alignment_reader.rs

This PR fixes an index error that occurs with bam files that include reads with hard clips.

Fix index error for hard clips

---

tests/expected/report/details/a/KRAS.html
tests/expected/report/details/b/KRAS.html
tests/expected/report/genes/KRAS1.html
tests/expected/report/indexes/index1.html
tests/lib.rs

Updating the version of rbt led to problems with the test for the vcf-report since the version is rendered into the navbar of all HTML files and the expected files still had a previous version in their navbar. This PR removes the version from the navbar of the expected files and also adjusts the test accordingly.

Fix report test

---

src/bcf/report/js/table-report.js
src/bcf/report/mod.rs
src/bcf/report/table_report/create_report_table.rs

This PR improves and simplifies the use of format tags in the custom JS file given by the user. With the lately added interface for multi-sample vcf-files, the `data-format` attribute was not updated. Now format values eg. `OBS` can be dressed in the JS in the the following way: `$(this).data("format")["OBS"][samplename]`.

Improve format tag data structure

---

src/bcf/report/mod.rs

This PR fixes a bug where `table-report.js` is missing when applying the default template file.

Fix default table template

---

CHANGELOG.md

This PR resolves an error in the changelog entry of version 0.5.0. Additionally it unifies some typesetting (all-capital file format names, commands `set-as-code`).

Fixed error in version description and minor cleanup.

---

src/bcf/report/table_report/create_report_table.rs
src/cli.yaml

As the title says it is now possible to define prefixes for INFO-field records by adding a `*` at the end of a record string.

Allow INFO-Field prefixes in vcf-report

---

Cargo.toml

This PR temporarily fixes a [problem](https://github.com/rust-rocksdb/rust-rocksdb/issues/479) with the latest `v1.0.63` of `cc` that stops `rust-rocksdb` from compiling by simply using an older version of `cc`.

Fix problems with latest cc version

---

Cargo.toml

This PR removes the explicit `cc` version from the `Cargo.toml` now that https://github.com/rust-rocksdb/rust-rocksdb/issues/479 is fixed with the release of `v1.0.65`.

Remove workaround for cc version v1.0.63

---

Cargo.toml
src/main.rs

When you have lots of samples, it takes quite some time to build all the individual table reports sequentially; this can be parallelised easily with rayon.

Parallelise `table_report` calls over samples

---

src/cli.yaml
src/main.rs

As requested by @johanneskoester in #98 this PR adds a `--threads` parameter to the vcf-report. As i haven't got much experience with [rayon](https://github.com/rayon-rs/rayon) it'd be great to know if i used it in the right way.

Add threads parameter to vcf-report

---

src/bcf/report/oncoprint.rs

This PR allows the usage of VCF files without the need of `CLIN_SIG` to be present in each file. In case it is not present in any of the files the plot is completely omitted. This also adds a proper error message in case the `ANN` field is not present at all.

Allow VCF files without CLIN_SIG

---

Cargo.toml
src/bcf/report/table_report/create_report_table.rs

Just a quick removal of the git dependency now that [lz-str](https://crates.io/crates/lz-str) got released to crates.io.

Remove git dependency

---

src/bcf/report/js/report.js
src/bcf/report/oncoprint.rs
src/bcf/report/table_report/create_report_table.rs

This PR allows records without `SYMBOL` or `Gene` fields present. Instead `HGVSg` will be used. Note that `HGVSg` **must** be present in order for the record to appear in the report. Records with displayed with `HGVSg` in the first stage of the report will directly link to the detail view of the report (only when a sample is selected by using the main matrix for navigation).

Allow no symbol or gene field

---

Cargo.toml
src/bcf/report/highlight_specs.json
src/bcf/report/info_specs.json
src/bcf/report/oncoprint.rs
src/bcf/report/table_report/create_report_table.rs
src/cli.rs
src/main.rs

This PR adds a new parameter `--plot-info`, that takes info keys of a vcf or bcf file that will be then added to the first and second stage of the report in form of a bar plot.

Add new parameter for additional bar plots

---

src/bcf/report/oncoprint.rs

This PR is makes the canonical field of vcfs, given to the vcf-report, optional.

Make canonical field optional

---

src/bcf/report/oncoprint.rs
src/bcf/report/table_report/create_report_table.rs

Just a quick improvement for a warning that now contains `chrom:pos` for the affected record, not the inner struct.

Improve warning for missing fields

---

src/bcf/report/oncoprint.rs

This PR removes the plot for `Existing_variation` in case it would only contain `unknown` values.

Remove existing variation plot if only unknown values appear

---

CHANGELOG.md
src/bcf/report/js/table-report.js
src/bcf/report/table_report/report_table.html.tera
tests/expected/report/details/a/KRAS.html
tests/expected/report/details/b/KRAS.html

This PR fixes a problem discovered by @FelixMoelder that made it impossible to add anything to the `#ann-sidebar` because it was fully cleared in the default template, which was imported (and therefore executed) after any additional js file given with `-l`. Additional js files are now imported afterwards and can add anything to the sidebar.

Change import order for additional js files

---

src/bcf/report/table_report/create_report_table.rs
src/bcf/report/table_report/fasta_reader.rs

This PR improves the fetching of fasta sequence lengths by using a `HashMap` with contig names as keys. This avoids iterating over each sequence over and over for every plot.

Improve fetching fasta sequence lengths

---

src/csv/report.rs

This PR fixes #131 by checking if values are empty before creating a prefix.

Fix index out of bounce error in csv-report

---

src/csv/csv_report.html.tera
src/csv/lookup_table.html.tera
src/csv/plot.js.tera
src/csv/prefix_table.html.tera
src/csv/report.rs

This PR renews the inner file structure of the css-report, especially the naming of folders and files corresponding to the columns of the csv file, which avoids possible errors due to long titles with spaces or generally titles containing special characters

Rework file naming for csv-report

---

CHANGELOG.md
src/bcf/report/table_report/plot.js.tera

This PR fixes a small syntax problem with the JSON object containing the plots for the third stage of the vcf-report.

Fix vcf-report plots for multi sample files

---

src/csv/csv_report.html.tera
src/csv/report.rs

This PR removes plots for columns with more than 10 unique nominal values that all occur equally often. Furthermore empty fields are discarded before being plotted as one occurring value.

Remove unreasonable plots

---

src/csv/report.rs

This PR fixes the filtering of empty values in nominal plots introduces in #139 by adding a missing negation to the filter statement.

Bugfix for nominal plots in csv-report

---

src/bcf/report/oncoprint.rs

This PR changes behaviour for multiple canonical records per gene in the vcf-report so that rbt only prints a warning and plots all canonical records instead of panicking  right away.

Change behaviour for multiple canonical records per gene in vcf-report

---

CHANGELOG.md
src/bcf/report/table_report/create_report_table.rs
src/bcf/report/table_report/static_reader.rs

This PR makes the vcf-report only plot reads overlaying the variant. This eliminates the potential risk of receiving a plot without any reads overlaying the variant when using `--max-read-depth`. Also includes a small fix that i discovered regarding the placement of single nucleobases of reads that do not match the reference genome.

Only plot reads overlaying the variant

---

src/bcf/report/table_report/create_report_table.rs
tests/expected/report/details/a/KRAS.html
tests/expected/report/details/b/KRAS.html

This PR fixes the shown position in the table of the vcf-report which was actually 0-based and is now corrected to 1-based.

Fix position in table-report

---

src/bcf/report/table_report/create_report_table.rs
src/bcf/report/table_report/fasta_reader.rs
src/main.rs

This PR fixes a problem with anyhow errors not being shown caused by this line:
https://github.com/rust-bio/rust-bio-tools/blob/1f337758a9d7a9c6d1b69eb25aea1972dd4cd0e9/src/main.rs#L200
I also added a missing anyhow error context for retrieving fasta lengths.

Fix anyhow errors for table-report

---

src/bam/plot/bam_plot.html.tera
src/bcf/report/table_report/fasta_reader.rs

This PR adds missing lowercase reference bases in plots for `rbt vcf-report` and `rbt plot-bam`. It also includes a quick improvement of the plot height of `rbt plot-bam` when there is only one given sample.

fix: Missing lowercase reference bases in reports

---

Cargo.toml

This removes the pinned version of xlsxwriter and libxlsxwriter-sys introduced before to fix https://github.com/informationsea/xlsxwriter-rs/issues/21.

refactor: Remove pinned xlsxwriter version

---

src/bcf/report/table_report/fasta_reader.rs
src/bcf/report/table_report/vegaSpecs.json

This PR marks lowercase bases as repeats with lower opacity in all vega plots generated with `rbt plot-bam` and `rbt vcf-report`.

feat: Mark repeats in reference with lower opacity

---

.github/workflows/release-please.yml

This should prevent PRs like [this one](https://github.com/fxwiegand/rust-bio-tools/pull/2). Not sure whether this is the most elegant way to deal with this. I've had a look at the configuration section in the [Release Please Documentation](https://github.com/google-github-actions/release-please-action) and only found a fork option (which should be `false` by default) that decides whether the PR is created **from** a fork but not **inside** one.  @johanneskoester let me know if you have a better idea! 😅

fix: Prevent release PR on forks

---

src/csv/csv_report.js.tera

This PR truncates long strings to 30 characters in each cell of the `rbt csv-report` table (if there is no custom formatter given from the user for the corresponding column). The whole content of the cell is still available via a popover with `overflow: auto`. This should reduce the overall size of the table. 
Example:

feat: Add ellipsis to csv-report

---

src/bcf/report/table_report/create_report_table.rs

This PR fixes a bug in `rbt vcf-report` where the `FASTA read interval was out of bounds` for long variants positioned at the end of the given FASTA reference.

fix: Adjust FASTA read interval

---

src/bcf/report/js/table-report.js

In the previous PR a Cosmic link for Cosmic-IDs starting with `COSV` had been added.
Unintentionally the `COSV` prefix had been striped from the ID causing the link to be invalid.

fix: Cosmic link

---

Cargo.toml

- SSE instructions are used according to the target CPU specifications
- via https://github.com/rust-rocksdb/rust-rocksdb/pull/526
- fixes https://github.com/bioconda/bioconda-recipes/pull/28719

fix: Respect target CPU compat via rocksdb ^0.17

---

src/bam/collapse_reads_to_fragments/pipeline.rs
src/bcf/report/table_report/static_reader.rs
src/csv/report.rs

This PR improves handling of softclips when executing `collapse_reads_to_fragments`.
Initially reads were skipped in case starting or trailing softclips as building consensus sequences might be non-deterministic.
Now, it turned out that softclips may also occur after hardclips (in case of primer trimming using fgbio).
In that case `collapse_reads_to_fragments` will fail as these reads won't be skipped.
To fix this cigar string will now be fully checked for softclips.
This PR also includes applies some clippy lints.

fix: improved handling of softclips

---

src/bcf/report/oncoprint.rs

This removes custom classifications for duplicates and inversions that generally follow their own semantic.

fix: remove custom classifications

---

src/bam/anonymize_reads.rs
src/bam/mod.rs
src/bam/simulate_reads.rs
src/cli.rs
src/main.rs

This PR adds a subcommand `rbt simulate-reads` allowing to derive artificial bam files from real ones.
The user has to define a region from which reads will be drawn. (Only read pairs that are completely within the region will be considered.)
For this region a random reference sequence will be created.
Artificial reads will then be derived from this random reference by comparing the original read sequence to the reference (based on cigar operations).
Mismatching bases are replaced by random ones that differ from the reference.
The final reads contain random sequences with positions readjusted to the new reference.
The following attributes will be adopted from the original read:
- read name
- base qualities
- flags
- CIGAR-String
- insert size
- MC tag
Creating artificial reads allows to …

feat: simulate reads from real bam files

---

src/bcf/report/table_report/fasta_reader.rs
src/bcf/report/table_report/vegaSpecs.json

This PR adds the position of reference bases to the tooltip. It also removes the redundant `start_position` and `end_position` attributes and uses vega transforms instead to generate it.

feat: Show position of reference base in tooltip

---

src/bcf/report/table_report/alignment_reader.rs

This PR makes neighboring insertion markers slightly smaller in order to not confuse them as a single insertion over two bases.

fix: Disconnect neighboring insertion markers

---

README.md

`cargo install rust-bio-tools` doesn't work without first installing gsl manually.

docs: Add `gsl` dependency in README

---

src/bcf/report/oncoprint.rs

This PR improves the gene search of the vcf-report by removing its prefix aspect as suggested by @FelixMoelder.

feat: Improve gene search for vcf-report

---

src/bcf/report/oncoprint.rs

This PR changes makes the vcf-report use `Feature` before `HGVSg` for level 1 naming in case `Gene` and `SYMBOL` are missing.

feat: Use Feature before HGVSg for vcf-report level 1 naming

---

src/bam/anonymize_reads.rs
src/bcf/match_variants.rs
src/bcf/report/oncoprint.rs
src/fastq/collapse_reads_to_fragments/pipeline.rs

This PR unifies the output of `bam-anonymize` by adapting the mandatory fields of the input file.
In addition, all aux fields are also copied to the anonymized reads in order to improve compatibility.
As there were some clippy warning about dead code these have been fixed.

feat: anonymize bam - adapt mandatory and aux fields

---

src/bam/plot/bam_plot.html.tera
src/bcf/report/js/table-report.js
src/bcf/report/table_report/alignment_reader.rs

This PR adds the aux field(s) of a bam record to the tooltip of any alignment plots generated with `rbt vcf-report` and `rbt plot-bam`. It also fixes the flags tooltip of `rbt plot-bam` that was not displayed correctly.

feat: Add aux field to tooltip

---

src/bcf/match_variants.rs
src/bcf/report/oncoprint.rs
src/bcf/report/table_report/alignment_reader.rs
src/bcf/report/table_report/create_report_table.rs
src/bcf/split.rs
src/common.rs
src/fastq/collapse_reads_to_fragments/pipeline.rs
tests/lib.rs

Just a quick PR that applies the latest lints from clippy.

fix: Apply latest clippy lints

---

src/csv/csv_report.html.tera

`Popper.js` is needed for popovers in bootstrap (see https://getbootstrap.com/docs/4.1/components/popovers/).
It should be included in `bootstrap.bundle.js`. However, in our reports over at [github.com/IKIM-Essen/uncovar](https://github.com/IKIM-Essen/uncovar) the popovers do not work (e.g., see 1. Overview -> 1. Report in a [report](https://github.com/IKIM-Essen/uncovar/suites/4921527977/artifacts/142056317) ). 
But if popper is included separately, the popovers are working.

fix: add popper in csv report

---

src/bcf/report/table_report/create_report_table.rs

This PR fixes the read plot height that was too large when creating report with the `--max-read-depth` parameter.

fix: Fix vcf-report read plot height when using --max-read-depth

---

src/bcf/report/oncoprint.rs

This PR fixes the width of the allele frequency heatmap in stage 2 of the vcf-report.

fix: Fix vcf-report allele frequency heatmap width

---

src/bcf/to_txt.rs
tests/lib.rs

…to-txt
The tag name in FORMAT field that causes panic is now printed (#52).

fix: Improved message if error occurred during FORMAT parsing in vcf-to-txt

---

Cargo.toml
src/bam/anonymize_reads.rs
src/bam/collapse_reads_to_fragments/mod.rs
src/bam/collapse_reads_to_fragments/pipeline.rs

When calculating consensus reads it happens that reads get skipped and directly written into a bam file.
As skipped records are expected to be used in downstream analysis it may happen that these reads are marked as duplicates while the remaining duplicates got merged into a consensus read.
In that case the marked reads would be ignored by variant callers.
To prevent this from happening reads the duplicate-flag will be removed from skipped reads and also the PicardTools specific tags: `DI`, `DS` and `PG`.

feat: Remove duplicate marks from consensus records

---

Cargo.toml
src/csv/report.rs

This PR updates xlsxwriter due to compilation error with older version and fixes #256.

build: Update xlsxwriter due to compilation error with older version
